"""Emulation of the Rust parameter checks, so that the tool emits only sets that Rust accepts.

`from_json` follows `TboxParams::from_json`: strict JSON decoding (`check_fields`), then
`check_params`, which follows `TboxParams::check` (`src/params/mod.rs`, `check_with`)
step by step, with its error strings. `check_compile` follows the parameter-dependent checks
of `statement::compile` (`src/statement.rs`) in its order: the witness dimensions, the
inverses of the statement and constraint moduli, for variables bounded in $`\\ell_\\infty`$ the
conditions on the extraction bound $`E`$ of `log_sigma[3]`, the lifting check of every lifted
constraint with its own modulus (`check_lifting_pairs`, at $`E`$ for constraints with such
variables), and the block checks of `lnp::Statement::check`; `lin_requirements` follows
`Statement::requirements` and `bounds` for a `lin::compile` statement whose public coefficients
all have the largest centred absolute value, which dominates every instance of the shape.
`prover_checks` holds the one check the prover makes beyond these (the Rej_1/Rej_2 constants
of `Abdlop::rejection_constants`).

Integer checks are exact. The f64 checks use Python floats, which are IEEE doubles as in Rust;
`log2`, `exp` and `pow` come from the platform's libm in both. A check that holds with a
relative margin below `GUARD` is reported, and the search treats it as failing. Rust errors
that are not `Error::Parameter` are reported as "encoding", "overflow" and "dimension".

Capacities follow the crate's source: prime factors and their product below $`2^{256}`$
(`TboxParams::prime_factors`, `Ring::with_modulus`), Gaussian exponents up to 100
(`rand::MAX_LOG_SIGMA`) and lifted coefficient bounds below $`2^{256}`$ (`statement::bounds`).
`NARROW_CAPACITY` holds narrower limits (`u64` factors, $`q<2^{100}`$, exponents up to 40,
bounds below $`2^{128}`$), under which the tests reach refusals that the crate's own limits
leave unreachable. Fields that Rust stores as `u64` (`gamma`, `alpha_squared`, `linf_bound`,
`l2_bounds_squared`) stay below $`2^{64}`$ under both.
"""
import math
import re
from pathlib import Path

from . import jsonio, modulus

GUARD = 1e-9
CAPACITY = {"prime_bits": 256, "q_bits": 256, "log_sigma": 100, "coefficient_bits": 256}
NARROW_CAPACITY = {"prime_bits": 64, "q_bits": 100, "log_sigma": 40, "coefficient_bits": 128}
CHALLENGE = {64: (8, 140, 5), 128: (2, 59, 3)}  # (omega, eta, challenge_bits)
NADDS = 128
U32, U64 = 1 << 32, 1 << 64
USIZE_FIELDS = ("degree", "m1", "m2", "l", "n_msis", "n_bin", "n_prime", "mlwe_rank")
U64_FIELDS = ("alpha_squared", "linf_bound", "gamma")


def _ntt_primes():
    """The RNS primes of `src/params/moduli.rs` (generated by tools/params/moduli.py), read
    from the crate so that the emulation follows the table; the original four as a fallback."""
    try:
        text = (Path(__file__).resolve().parents[3] / "src" / "params" / "moduli.rs").read_text()
        primes = tuple(int(p) for p, _ in re.findall(r"\((\d+), (\d+)\)", text))
        if primes:
            return primes
    except OSError:
        pass
    return (4611686018427365377, 4611686018427322369, 4611686018427289601, 4611686018427277313)


NTT_PRIMES = _ntt_primes()


class RustCheckError(ValueError):
    """A check that Rust would fail, with Rust's message."""

    def __init__(self, message, detail=None):
        super().__init__(message if detail is None else f"{message}: {detail}")
        self.rust_message = message


class Checks:
    """Records every inequality as (name, lhs, rhs, relation, holds, relative margin)."""

    def __init__(self):
        self.rows = []
        self.floats = {}  # Rust's f64 outputs of `check` (arp_bound, msis_delta)

    def add(self, name, lhs, rhs, relation, message):
        lhs_f, rhs_f = float(lhs), float(rhs)
        holds = {"<": lhs < rhs, "<=": lhs <= rhs, ">": lhs > rhs, ">=": lhs >= rhs}[relation]
        big, small = (rhs_f, lhs_f) if relation in ("<", "<=") else (lhs_f, rhs_f)
        margin = (big - small) / abs(big) if big else 0.0
        self.rows.append({"name": name, "lhs": lhs, "rhs": rhs, "relation": relation,
                          "holds": holds, "relative_margin": margin, "message": message})
        if not holds:
            raise RustCheckError(message, f"{name}: {lhs!r} {relation} {rhs!r} fails")

    def tight(self, guard=None):
        """Floating-point checks that hold with a relative margin below `guard` (default
        `GUARD`, read at call time)."""
        guard = GUARD if guard is None else guard
        return [r["name"] for r in self.rows
                if r.get("float") and r["relative_margin"] < guard]

    def mark_float(self):
        self.rows[-1]["float"] = True


def _uint(v, limit):
    return isinstance(v, int) and not isinstance(v, bool) and 0 <= v < limit


def check_fields(p):
    """The field types of `TboxParams` that JSON decoding enforces: strings, `usize` and `u32`
    fields, `u64` bounds, prime factors below $`2^{256}`$, four exponents and a float delta.
    Rust fails such input with `Error::Encoding`."""
    if not isinstance(p.get("id"), str) or not isinstance(p.get("estimator"), str):
        raise RustCheckError("encoding", "id and estimator must be strings")
    f = p.get("prime_factors")
    if not isinstance(f, list) or not all(_uint(x, 1 << 256) for x in f):
        raise RustCheckError("encoding", "prime factors must be integers below 2^256")
    for key in USIZE_FIELDS:
        if not _uint(p.get(key), U64):
            raise RustCheckError("encoding", f"{key} must be a usize")
    for key in U64_FIELDS:
        if not _uint(p.get(key), U64):
            raise RustCheckError("encoding", f"{key} must be a u64")
    if not isinstance(p.get("l2_rows"), list) or not all(_uint(x, U64) for x in p["l2_rows"]):
        raise RustCheckError("encoding", "l2_rows must be usize values")
    b = p.get("l2_bounds_squared")
    if not isinstance(b, list) or not all(_uint(x, U64) for x in b):
        raise RustCheckError("encoding", "l2_bounds_squared must be u64 values")
    ls = p.get("log_sigma")
    if not isinstance(ls, list) or len(ls) != 4 or not all(_uint(x, U32) for x in ls):
        raise RustCheckError("encoding", "log_sigma must be four u32 values")
    if not _uint(p.get("d_bits"), U32):
        raise RustCheckError("encoding", "d_bits must be a u32")
    delta = p.get("mlwe_delta")
    if isinstance(delta, bool) or not isinstance(delta, (int, float)):
        raise RustCheckError("encoding", "mlwe_delta must be a number")


def from_json(text, capacity=CAPACITY):
    """`TboxParams::from_json`: strict decoding, then the checks. Returns (params, derived,
    Checks); decoding failures raise the "encoding" error."""
    try:
        p = jsonio.load_params(text)
    except (ValueError, TypeError) as e:
        raise RustCheckError("encoding", str(e)) from None
    derived, checks = check_params(p, capacity)
    return p, derived, checks


def range_rejection_constant(log_sigma, alpha_squared, max_log_sigma=CAPACITY["log_sigma"]):
    """`params::range_rejection_constant`."""
    if log_sigma > max_log_sigma:
        raise RustCheckError("Gaussian width capacity")
    sigma = 1.55 * 2.0 ** log_sigma
    try:
        m = math.ceil(math.exp(337.0 * float(alpha_squared) / (2.0 * sigma * sigma)) + 1e-10)
    except OverflowError:
        raise RustCheckError("range rejection M") from None
    if m >= 65536:
        raise RustCheckError("range rejection M", f"M = {m}")
    return m


def power2round_high(q, d_bits, r):
    """`Compression::power2round(r).0` with `center` to $`(-2^{D-1},2^{D-1}]`$."""
    r %= q
    power = 1 << d_bits
    low = r % power
    if low > power // 2:
        low -= power
    return (r - low) // power


def rns_primes_required(q, d):
    """Number of NTT primes `Ring::new` takes: the first prefix whose product exceeds
    $`(q-1)^2\\cdot d\\cdot128+1`$, or None when all of them do not suffice."""
    bound = (q - 1) ** 2 * d * NADDS + 1
    product = 1
    for count, prime in enumerate(NTT_PRIMES, 1):
        product *= prime
        if product > bound:
            return count
    return None


def rust_lambda(q1):
    """The repetition count $`\\lambda`$ as `TboxParams::check` computes it (`params/mod.rs`):
    the smallest even $`\\lambda\\ge2`$ with $`\\lambda\\log_2 q_1\\ge128`$, where the
    logarithm is taken of the f64 nearest $`q_1`$ (`int::to_f64` rounds to nearest). For
    $`2^{64}-46080\\le q_1<2^{64}`$ that logarithm is 64.0, so $`\\lambda=2`$ there, while the
    exact logarithm gives 4."""
    lam = 2
    log_q1 = math.log2(float(q1))
    while lam * log_q1 < 128.0:
        lam += 2
    return lam


def check_params(p, capacity=CAPACITY):
    """Emulate `TboxParams::check`. Returns (derived values, Checks). Raises RustCheckError."""
    check_fields(p)
    c = Checks()
    if not p["id"] or len(p["id"].encode()) > 256 or not p["estimator"] \
            or len(p["estimator"].encode()) > 4096:
        raise RustCheckError("parameter provenance")
    f = p["prime_factors"]
    if len(f) not in (1, 2) or any(x % 8 != 5 for x in f) \
            or any(x >= 1 << capacity["prime_bits"] for x in f) \
            or any(not (modulus.rust_is_prime(x) if x < U64 else modulus.is_prime(x))
                   for x in f) \
            or any(a >= b for a, b in zip(f, f[1:])):
        raise RustCheckError("proof modulus factors")
    q = math.prod(f)
    if q >= 1 << capacity["q_bits"]:
        raise RustCheckError("overflow" if capacity["q_bits"] >= 256 else "ring modulus")
    d = p["degree"]
    if d not in (64, 128):
        raise RustCheckError("proof degree")
    if rns_primes_required(q, d) is None:
        raise RustCheckError("overflow", "not enough RNS primes")
    gamma, d_bits = p["gamma"], p["d_bits"]
    if not (3 <= q < 1 << capacity["q_bits"]) or q % 2 == 0 or gamma < 2 or gamma % 2 \
            or (q - 1) % gamma or d_bits >= capacity["q_bits"] or (1 << d_bits) >= q:
        raise RustCheckError("compression")
    q_bits = (q - 1).bit_length()
    if power2round_high(q, d_bits, q - 1) >= 1 << (q_bits - d_bits):
        raise RustCheckError("compressed commitment bit width")
    z = len(p["l2_rows"])
    if z != len(p["l2_bounds_squared"]) or z > 1024 or 0 in p["l2_rows"] \
            or 0 in p["l2_bounds_squared"]:
        raise RustCheckError("exact norm blocks")
    dims = [p["m1"], p["m2"], p["l"], p["n_msis"], p["n_bin"], p["n_prime"], p["mlwe_rank"]]
    if any(x > 65535 for x in dims + list(p["l2_rows"])) or p["n_msis"] == 0 \
            or p["m2"] <= p["n_msis"] or p["alpha_squared"] == 0:
        raise RustCheckError("dimensions")
    if (p["n_prime"] == 0) != (p["linf_bound"] == 0):
        raise RustCheckError("approximate block")
    ls = p["log_sigma"]
    if any(t > capacity["log_sigma"] for t in ls):
        raise RustCheckError("Gaussian width capacity")
    lam = rust_lambda(f[0])
    omega, eta, challenge_bits = CHALLENGE[d]
    n_ex = p["n_bin"] + sum(p["l2_rows"]) + z
    if len(f) > 1 and (n_ex > 0 or p["n_prime"] > 0):
        raise RustCheckError("binary, exact-norm and range blocks require a prime modulus")
    exact_slots = 256 // d if n_ex > 0 else 0
    approx_slots = 256 // d if p["n_prime"] > 0 else 0
    l_ext = exact_slots + approx_slots + 1 + lam // 2 + 1
    c.add("completeness (m1+Z)d", (p["m1"] + z) * d, 640, ">=", "completeness dimensions")
    c.add("completeness m2 d", p["m2"] * d, 640, ">=", "completeness dimensions")
    if p["m2"] - (p["n_msis"] + p["l"] + l_ext) != p["mlwe_rank"] or p["mlwe_rank"] == 0:
        raise RustCheckError("simulatability rank")
    delta = p["mlwe_delta"]
    if not (math.isfinite(delta) and 1.0 <= delta <= 1.0044):
        raise RustCheckError("MLWE estimate")
    s1, s2, s3, s4 = (1.55 * 2.0 ** t for t in ls)
    nd = float(p["n_msis"] * d)
    b = s2 * math.sqrt(float(2 * p["m2"] * d))
    b = b + eta * 2.0 ** (d_bits - 1) * math.sqrt(nd) + gamma * math.sqrt(nd) / 2.0
    if not math.isfinite(b):
        raise RustCheckError("compressed response bound capacity")
    c.add("response bound b^2", b * b, 2.0 ** 128, "<", "compressed response bound capacity")
    c.mark_float()
    b1 = 2.0 * s1 * math.sqrt(float(2 * (p["m1"] + z) * d))
    bound = 4.0 * eta * math.sqrt(b1 * b1 + 4.0 * b * b)
    msis_delta = 2.0 ** (math.log2(bound) ** 2 / (4.0 * nd * math.log2(float(q))))
    c.add("MSIS delta", msis_delta, 1.0044, "<", "MSIS estimate")
    c.mark_float()
    c.add("MSIS bound < q", bound, float(q), "<", "MSIS estimate")
    c.mark_float()
    c.add("rounding 2^(D-1) omega d < gamma", 2.0 ** (d_bits - 1) * omega * d, float(gamma), "<",
          "rounding bound")
    c.mark_float()
    exact_alpha_sq = (p["n_bin"] + z) * d + sum(p["l2_bounds_squared"])
    approx_alpha_sq = p["linf_bound"] ** 2 * p["n_prime"] * d
    if exact_alpha_sq >= 1 << 128 or approx_alpha_sq >= 1 << 128:
        raise RustCheckError("overflow", "range alpha squared")
    cap_ls = capacity["log_sigma"]
    m3 = range_rejection_constant(ls[2], exact_alpha_sq, cap_ls) if n_ex > 0 else None
    m4 = range_rejection_constant(ls[3], approx_alpha_sq, cap_ls) if p["n_prime"] > 0 else None
    z4_bound = (124 << ls[3]) // 5
    arp = 2.0 * math.sqrt(256.0 / 26.0) * 1.64 * s3
    qf = float(q)
    if n_ex > 0:
        c.add("ARP modulus bound", qf, 41.0 * float(n_ex * d) * arp, ">=", "ARP modulus bound")
        c.mark_float()
        c.add("binary lifting bound", qf, arp * arp + arp * math.sqrt(float(p["n_bin"] * d)), ">",
              "binary lifting bound")
        c.mark_float()
        c.add("slack lifting bound", qf, arp * arp + arp * math.sqrt(float(d)), ">",
              "slack lifting bound")
        c.mark_float()
        for i, bsq in enumerate(p["l2_bounds_squared"]):
            c.add(f"exact norm lifting bound {i}", qf, 3.0 * float(bsq) + arp * arp, ">",
                  "exact norm lifting bound")
            c.mark_float()
    log_q = (q - 1).bit_length()

    def gaussian_bits(s):
        return math.ceil(math.log2(s) + 2.5)
    bits = nd * float(log_q - d_bits) \
        + float((p["l"] + l_ext + lam // 2) * d) * float(log_q) \
        + float(challenge_bits * d) \
        + float((p["m1"] + z) * d) * gaussian_bits(s1) \
        + float((p["m2"] - p["n_msis"]) * d) * gaussian_bits(s2) \
        + float(exact_slots * d) * gaussian_bits(s3) \
        + float(approx_slots * d) * gaussian_bits(s4) \
        + hint_bits(s2, gamma) * nd
    z1 = (961 << (2 * ls[0])) * (2 * (p["m1"] + z) * d) // 400
    z3 = ((656 * 656 * 961) << (2 * ls[2])) // 250000
    if max(z1, z3, 2 * z4_bound) >= 1 << 128:
        raise RustCheckError("response bound capacity")
    rej1, rej2 = rejection_constants(p, eta)
    derived = {
        "q": q, "lambda": lam, "omega": omega, "eta": eta, "n_ex": n_ex, "l_ext": l_ext,
        "b_squared": math.floor(b * b),
        "z1_bound_squared": z1, "z3_bound_squared": z3,
        "z4_bound": z4_bound, "exact_alpha_squared": exact_alpha_sq,
        "approx_alpha_squared": approx_alpha_sq, "approx_extraction_bound": 2 * z4_bound,
        "rejection_M1": rej1, "rejection_M2": rej2,
        "range_rejection_M3": m3, "range_rejection_M4": m4,
        "estimated_proof_bytes": math.ceil(bits / 8.0),
        "rns_primes_required": rns_primes_required(q, d),
    }
    c.floats = {"arp_bound": arp, "msis_delta": msis_delta}
    return derived, c


def hint_bits(sigma2, gamma):
    """Bits per hint coefficient of the size estimate, as `params::hint_bits`:
    $`\\max(2.25,1.6s+0.7)`$ for $`s=\\sigma_2/\\gamma`$, an upper bound on the expected hint
    length when $`z_{22}/\\gamma`$ is a normal of deviation $`s`$ plus a uniform rounding error;
    2.25 bits is the average that LNP22 Section 6.1 takes from the Dilithium paper (Ducas et
    al., ePrint 2017/633) for hints in $`\\{-1,0,1\\}`$. Division, product and sum are correctly
    rounded in both languages, so the double is Rust's bit for bit."""
    return max(2.25, 1.6 * (sigma2 / float(gamma)) + 0.7)


def rejection_constants(p, eta):
    """`Abdlop::rejection_constants`: the integer ceilings of Rej_1 (z1) and Rej_2 (z2); None
    for a constant that overflows f64."""
    s1 = 1.55 * 2.0 ** p["log_sigma"][0]
    s2 = 1.55 * 2.0 ** p["log_sigma"][1]
    alpha = float(p["alpha_squared"]) + float(len(p["l2_rows"]) * p["degree"])
    g1 = s1 / (eta * math.sqrt(alpha))
    g2 = s2 / (eta * math.sqrt(float(p["m2"] * p["degree"])))
    out = []
    for x in (math.sqrt(258.0 * math.log(2.0)) / g1 + 0.5 / (g1 * g1), 0.5 / (g2 * g2)):
        try:
            out.append(math.ceil(math.exp(x) + 1e-10))
        except OverflowError:
            out.append(None)
    return out[0], out[1]


def prover_checks(derived):
    """The prover's own refusal beyond `check`: Rej_1 and Rej_2 constants below $`2^{16}`$
    (`Abdlop::rejection_constants`), so that an accepted set can also prove."""
    for key in ("rejection_M1", "rejection_M2"):
        if derived[key] is None or derived[key] >= 65536:
            raise RustCheckError("rejection constant capacity", f"{key} = {derived[key]}")


def extraction_bound(log_sigma3):
    """`approx_extraction_bound` of `TboxParams::check`: $`E=2\\lfloor124\\cdot2^{t_4}/5\\rfloor`$,
    the bound that extraction gives every range row (LNP22 Lemma 2.7)."""
    return 2 * ((124 << log_sigma3) // 5)


def linf_f(entry, e):
    """$`F_j(E)`$ of a `statement::LinfLifting` entry (modulus, exact, linear, quadratic)."""
    _, exact, linear, quadratic = entry
    return exact + linear * e + quadratic * e * e


def psi(p):
    """$`\\psi=\\lceil28\\cdot1.55\\cdot2^{t_4}/\\beta_\\infty\\rceil`$ in f64, as `compile`
    computes it, or the "lifting slack" refusal."""
    value = math.ceil(28.0 * 1.55 * 2.0 ** p["log_sigma"][3] / float(p["linf_bound"]))
    if value > float(2 ** 64 - 1):
        raise RustCheckError("lifting slack")
    return value


def lifting_rhs(p, pairs, linf=()):
    """The largest right-hand side of the lifting check of `compile`:
    $`2(F_j+p_j\\beta_\\infty\\psi)`$ over the lifted moduli with their honest bounds and
    $`2(F_j(E)+p_j\\beta_\\infty\\psi)`$ over the constraints with $`\\ell_\\infty`$ variables,
    with $`E`$ of the parameters' `log_sigma[3]`."""
    slack = p["linf_bound"] * psi(p)
    e = extraction_bound(p["log_sigma"][3])
    return max([2 * (f + m * slack) for m, f in pairs]
               + [2 * (linf_f(x, e) + x[0] * slack) for x in linf])


def check_lifting(p, max_f, max_v, statement_modulus, checks=None):
    """The lifting checks of `statement::compile` for a statement over another modulus:
    `max_v <= linf_bound` and
    $`q>2(F+p\\,\\beta_\\infty\\lceil28\\sigma_4/\\beta_\\infty\\rceil)`$ with $`\\psi`$
    computed in f64 as Rust does and the rest exactly (Rust compares in 1024 bits, so a
    right-hand side of $`2^{256}`$ or more fails this check). Returns the right-hand side.
    `check_lifting_pairs` is the form with a bound per constraint modulus."""
    return check_lifting_pairs(p, [[statement_modulus, max_f]], max_v, checks=checks)


def check_lifting_pairs(p, pairs, max_v, linf=(), checks=None):
    """`check_lifting` with one bound per lifted modulus (`pairs` of modulus and largest honest
    $`F_j`$) and the constraints with $`\\ell_\\infty`$ variables (`linf`, bounded at the
    extraction bound $`E`$), each with its own modulus, as `compile` checks every lifted
    constraint. Returns the largest right-hand side."""
    c = checks or Checks()
    q = math.prod(p["prime_factors"])
    if max_v > p["linf_bound"]:
        raise RustCheckError("carry or quotient bound")
    rhs = lifting_rhs(p, pairs, linf)
    c.add("modulus lifting bound", q, rhs, ">", "modulus lifting bound")
    return rhs


def full_lifting(lifting):
    """A lifting description with every field of `request.requirements_of`. The short form with
    only `statement_modulus` and `max_integer_coefficient` means that every constraint is
    lifted at the statement modulus."""
    if lifting is None or "pairs" in lifting:
        return lifting
    p, f = lifting["statement_modulus"], lifting["max_integer_coefficient"]
    return {"statement_modulus": p, "max_integer_coefficient": f, "pairs": [[p, f]], "linf": [],
            "extraction_limit": None, "has_linf": False, "betas": [], "lifted": True}


def single_modulus_lifting(req, statement_modulus, q):
    """The lifting of requirements that name one statement modulus: every lifted constraint at
    it, as `request.requirements_of` describes it."""
    lifted = bool(req["n_prime"]) and statement_modulus != q
    f = req.get("max_integer_coefficient", 0)
    return {"statement_modulus": statement_modulus, "max_integer_coefficient": f,
            "pairs": [[statement_modulus, f]] if lifted else [], "linf": [],
            "extraction_limit": None, "has_linf": False, "betas": [], "lifted": lifted}


def ceil_sqrt(x):
    r = math.isqrt(x)
    return r if r * r == x else r + 1


def lin_requirements(proof_degree, proof_modulus, statement_degree, statement_modulus, rows,
                     blocks, public_linf=None, capacity=CAPACITY):
    """`Statement::requirements` for the statement `lin::compile` builds from
    $`Aw+t=0`$ with `rows` equations, in the worst case over public data: every coefficient of
    $`A`$ and $`t`$ has absolute value `public_linf` (default $`\\lfloor p/2\\rfloor`$, the largest
    centred value). `blocks` is a list of (name, length, norm) with norm ("l2_squared", b),
    ("binary",) or ("unbounded",). Returns the requirements with `max_integer_coefficient`."""
    if proof_degree not in (64, 128) or statement_degree % proof_degree or proof_modulus < 2:
        raise RustCheckError("target ring")
    p = statement_modulus
    c = p // 2 if public_linf is None else public_linf
    k = statement_degree // proof_degree
    req = {"m1": 0, "l": 0, "alpha_squared": 0, "n_bin": 0, "l2_rows": [],
           "l2_bounds_squared": [], "n_prime": 0, "linf_bound": 0, "max_integer_coefficient": 0}
    betas = []
    for _name, length, norm in blocks:
        if norm[0] == "l2_squared":
            req["m1"] += length * k
            req["l2_rows"].append(length * k)
            req["l2_bounds_squared"].append(norm[1])
            req["alpha_squared"] += norm[1]
            betas.append((length, norm[1]))
        elif norm[0] == "binary":
            req["m1"] += length * k
            req["n_bin"] += length * k
            req["alpha_squared"] += length * statement_degree
            betas.append((length, length * statement_degree))
        elif norm[0] == "unbounded":
            req["l"] += length * k
            betas.append((length, None))
        else:
            raise ValueError(f"unknown norm {norm!r}")
    if proof_modulus != p and rows:  # without equations nothing is lifted (n_prime = 0)
        f = c
        for length, beta in betas:
            if c and beta is None:
                raise RustCheckError("unbounded variable in lifted relation")
            if c:
                f += length * ceil_sqrt(statement_degree * c * c * beta)
        if f >= 1 << capacity["coefficient_bits"]:
            raise RustCheckError("overflow", "lifted coefficient bound")
        req["n_prime"] = rows * k
        req["max_integer_coefficient"] = f
        req["linf_bound"] = max(1, -(-f // p))
    return req


def check_compile(p, req, statement_modulus, checks=None, lifting=None):
    """The parameter-dependent checks of `statement::compile` against requirements `req`
    (with `max_integer_coefficient`) and their `lifting` (`request.requirements_of`; without
    it, every lifted constraint at `statement_modulus`), in Rust's order: norm budget, witness
    dimensions, the inverses of the statement modulus and the constraint moduli, for
    $`\\ell_\\infty`$ variables their bound, the range condition's limit on the extraction
    bound $`E`$ and $`2E+1<q`$, the lifting checks, then the block checks of
    `lnp::Statement::check` (exact blocks, binary and range rows equal to the parameters').
    Returns the lifting right-hand side or None.

    Requirements are exported for one proof modulus, at which constraints over it are native;
    a set whose $`q`$ is one of the lifted moduli would compile another shape, and is refused
    here as "shape", a message Rust does not have. A constraint over the export's own modulus
    leaves no trace in the requirements; a request's `export_modulus` pins $`q`$ for such a
    statement (`request.check_export_modulus`)."""
    if req["alpha_squared"] > p["alpha_squared"]:
        raise RustCheckError("bounded witness norm budget")
    if p["m1"] != req["m1"] or p["l"] != req["l"]:
        raise RustCheckError("compiled witness dimensions")
    q = math.prod(p["prime_factors"])
    lifting = full_lifting(lifting) or single_modulus_lifting(req, statement_modulus, q)
    pairs = lifting["pairs"] if lifting["lifted"] else []
    if any(m == q for m, _ in pairs):
        raise RustCheckError("shape", "q is a lifted constraint modulus of the requirements")
    # compile inverts the statement modulus first, then every constraint modulus but q.
    if statement_modulus is not None and statement_modulus != q and statement_modulus % q == 0:
        raise RustCheckError("noninvertible statement modulus")
    if any(m % q == 0 for m, _ in pairs):
        raise RustCheckError("noninvertible constraint modulus")
    if lifting["has_linf"]:
        if any(beta > p["linf_bound"] for beta in lifting["betas"]):
            raise RustCheckError("approximate range bound")
        e = extraction_bound(p["log_sigma"][3])
        limit = lifting["extraction_limit"]
        if limit is not None and e > limit:
            raise RustCheckError("variable range above statement modulus")
        if 2 * e + 1 >= q:
            raise RustCheckError("approximate extraction bound")
    rhs = None
    if pairs:
        max_v = max(-(-f // m) for m, f in pairs)
        rhs = check_lifting_pairs(p, pairs, max_v, lifting["linf"], checks)
    if len(req["l2_rows"]) != len(p["l2_rows"]) or (req["n_bin"] > 0) != (p["n_bin"] > 0) \
            or (req["n_prime"] > 0) != (p["n_prime"] > 0):
        raise RustCheckError("dimension", "statement blocks differ from the parameters")
    for i, (rows, bsq) in enumerate(zip(req["l2_rows"], req["l2_bounds_squared"])):
        if bsq != p["l2_bounds_squared"][i]:
            raise RustCheckError("exact block bound")
        if rows != p["l2_rows"][i]:
            raise RustCheckError("dimension", f"exact block {i} rows")
    if req["n_bin"] != p["n_bin"] or req["n_prime"] != p["n_prime"]:
        raise RustCheckError("dimension", "binary or range rows")
    return rhs
